/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grasset.view;

import com.grasset.user.ManagerUser;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrique
 */
public class AdminJPanelView extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanelView
     */
    public AdminJPanelView() {
        initComponents();
        configureTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTableManager = new javax.swing.JTable();
        jLabelName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldSearch = new javax.swing.JTextField();
        jCheckBoxStatus = new javax.swing.JCheckBox();
        jLabelStatus = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jTextFieldCode = new javax.swing.JTextField();
        jLabelCode = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion D'accès", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 24))); // NOI18N
        setMaximumSize(new java.awt.Dimension(770, 700));
        setMinimumSize(new java.awt.Dimension(770, 700));
        setPreferredSize(new java.awt.Dimension(770, 700));

        jTableManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Prenom", "Nom", "Status", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableManager.setAlignmentX(0.0F);
        jTableManager.setAlignmentY(0.0F);
        jTableManager.setColumnSelectionAllowed(true);
        jTableManager.setPreferredSize(new java.awt.Dimension(400, 200));
        jScrollPane.setViewportView(jTableManager);
        jTableManager.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabelName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelName.setText("Prénom:");

        jLabelLastName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelLastName.setText("Nom:");

        jTextFieldSearch.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jCheckBoxStatus.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jCheckBoxStatus.setText("Actif");

        jLabelStatus.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelStatus.setText("Status:");

        jButtonSave.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonSave.setText("Enregistrer");

        jButtonDelete.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonDelete.setText("Supprimer");

        jButtonClear.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonClear.setText("Nettoyer");

        jLabelCode.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelCode.setText("Code:");

        jLabelPassword.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelPassword.setText("Mot de Passe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabelCode)
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabelPassword)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabelLastName))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelStatus)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jCheckBoxStatus)))
                        .addGap(54, 54, 54)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jButtonClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelCode))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCode, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jPasswordField))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabelName)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelLastName)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jCheckBoxStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxStatus;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableManager;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables

    // JTABLE
    private void configureTable() {
        jTableManager.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTableManager.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableManager.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableManager.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableManager.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableManager.getColumnModel().getColumn(4).setPreferredWidth(200);
    }

    public Integer actualSelectedVenue = null;

    public void updateTable(Set<ManagerUser> userSet) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableManager.getModel();
        int size = defaultTableModel.getRowCount();
        for (int i = 0; i < size; i++) {
            defaultTableModel.removeRow(0);
        }

        if (!userSet.isEmpty()) {
            userSet.stream().map((managerUser) -> {
                Object[] obj = new Object[5];
                obj[0] = managerUser.getCode();
                obj[1] = managerUser.getName();
                obj[2] = managerUser.getLastName();
                obj[3] = managerUser.isActive() ? "Actif" : "Non Actif";
                
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");                
                Date date;
                if (managerUser.getModificationDate() == null) {
                    date = managerUser.getCreationDate();
                } else {
                    date = managerUser.getModificationDate();
                }
                String fomatedDate = df.format(date);
                obj[4] = fomatedDate;
                
                return obj;
            }).forEachOrdered((obj) -> {
                defaultTableModel.addRow(obj);
            });

            actualSelectedVenue = 0;
            jTableManager.setRowSelectionInterval(0, actualSelectedVenue);
        }
    }

    public void setFields(ManagerUser managerUser) {
        if (managerUser != null) {
            jTextFieldCode.setText(managerUser.getCode());
            //jPasswordField.setText(managerUser.getPassword());
            jTextFieldName.setText(managerUser.getName());
            jTextFieldLastName.setText(managerUser.getLastName());
            jCheckBoxStatus.setSelected(managerUser.isActive());
        }
    }
    // JTABLE

    public JButton getjButtonClear() {
        return jButtonClear;
    }

    public JButton getjButtonDelete() {
        return jButtonDelete;
    }

    public JButton getjButtonSave() {
        return jButtonSave;
    }

    public JCheckBox getjCheckBoxStatus() {
        return jCheckBoxStatus;
    }

    public JTextField getjTextFieldCode() {
        return jTextFieldCode;
    }

    public JTextField getjTextFieldLastName() {
        return jTextFieldLastName;
    }

    public JTextField getjTextFieldName() {
        return jTextFieldName;
    }

    public JTextField getjTextFieldSearch() {
        return jTextFieldSearch;
    }

    public JPasswordField getjPasswordField() {
        return jPasswordField;
    }

    public JTable getjTable() {
        return jTableManager;
    }

}
