/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grasset.view;

import com.grasset.book.Author;
import com.grasset.book.Book;
import com.grasset.book.BookEdition;
import com.grasset.book.BookSample;
import com.grasset.reservation.BookReservation;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 *
 * @author henrique
 */
public class ClientJPanelView extends javax.swing.JPanel {

    /**
     * Creates new form ClientJPanelView
     */
    public ClientJPanelView() {
        initComponents();

        configureTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelInfo = new javax.swing.JPanel();
        jScrollPaneReservation = new javax.swing.JScrollPane();
        jTableReservations = new javax.swing.JTable();
        jTextFieldClientSearch = new javax.swing.JTextField();
        jLabelClientName = new javax.swing.JLabel();
        jTextFieldClientName = new javax.swing.JTextField();
        jLabelClientAddress = new javax.swing.JLabel();
        jTextFieldClientAddress = new javax.swing.JTextField();
        jLabelClientCity = new javax.swing.JLabel();
        jTextFieldClientCity = new javax.swing.JTextField();
        jTextFieldClientState = new javax.swing.JTextField();
        jLabelClientState = new javax.swing.JLabel();
        jLabelCountry = new javax.swing.JLabel();
        jTextFieldCountry = new javax.swing.JTextField();
        jLabelClientEmail = new javax.swing.JLabel();
        jTextFieldClientEmail = new javax.swing.JTextField();
        jTextFieldClientPhone = new javax.swing.JTextField();
        jLabelClientPhone = new javax.swing.JLabel();
        jLabelClientLastName = new javax.swing.JLabel();
        jTextFieldClientLastName = new javax.swing.JTextField();
        jLabelClientZIPCode = new javax.swing.JLabel();
        jTextFieldZIPCode = new javax.swing.JTextField();
        jSeparatorClientAddress = new javax.swing.JSeparator();
        jSeparatorClientInfo = new javax.swing.JSeparator();
        jLabelClientDocConfirmation = new javax.swing.JLabel();
        jTextFieldDocVerification = new javax.swing.JTextField();
        jCheckBoxValid = new javax.swing.JCheckBox();
        jLabelClientCode = new javax.swing.JLabel();
        jTextFieldClientCode = new javax.swing.JTextField();
        jButtonInfoReload = new javax.swing.JButton();
        jButtonInfoRenew = new javax.swing.JButton();
        jButtonInfoCancel = new javax.swing.JButton();
        jPanelBooks = new javax.swing.JPanel();
        jScrollPaneBook = new javax.swing.JScrollPane();
        jTableBooks = new javax.swing.JTable();
        jTextFieldBookSearch = new javax.swing.JTextField();
        jLabelBookISBN = new javax.swing.JLabel();
        jLabelBookTitle = new javax.swing.JLabel();
        jLabelBookAuthors = new javax.swing.JLabel();
        jLabelBookYear = new javax.swing.JLabel();
        jLabelBookEditor = new javax.swing.JLabel();
        jLabelTotalSamples = new javax.swing.JLabel();
        jTextFieldBookTitle = new javax.swing.JTextField();
        jTextFieldBookAuthors = new javax.swing.JTextField();
        jTextFieldBookYear = new javax.swing.JTextField();
        jTextFieldBookISBN = new javax.swing.JTextField();
        jTextFieldEditor = new javax.swing.JTextField();
        jTextFieldTotalSamples = new javax.swing.JTextField();
        jCheckBoxRare = new javax.swing.JCheckBox();
        jButtonBookReload = new javax.swing.JButton();
        jButtonBookReserve = new javax.swing.JButton();
        jLabelEditionYear = new javax.swing.JLabel();
        jTextFieldEditionYear = new javax.swing.JTextField();
        jLabelBookEdition = new javax.swing.JLabel();
        jTextFieldBookEdition = new javax.swing.JTextField();
        jLabelBookFormat = new javax.swing.JLabel();
        jTextFieldBookFormat = new javax.swing.JTextField();
        jLabelNumberPages = new javax.swing.JLabel();
        jTextFieldNumberPages = new javax.swing.JTextField();
        jLabelOriginalLanguage = new javax.swing.JLabel();
        jTextFieldOriginalLanguage = new javax.swing.JTextField();
        jLabelEditionLanguage = new javax.swing.JLabel();
        jTextFieldEditionLanguage = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1072, 578));
        setMinimumSize(new java.awt.Dimension(1072, 578));
        setPreferredSize(new java.awt.Dimension(1072, 578));

        jPanelInfo.setLayout(null);

        jTableReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Code Client", "ISBN", "Nom du Livre", "Date Reservation", "Status", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneReservation.setViewportView(jTableReservations);

        jPanelInfo.add(jScrollPaneReservation);
        jScrollPaneReservation.setBounds(0, 340, 1040, 200);
        jPanelInfo.add(jTextFieldClientSearch);
        jTextFieldClientSearch.setBounds(6, 294, 1050, 40);

        jLabelClientName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientName.setText("Prénom:");
        jPanelInfo.add(jLabelClientName);
        jLabelClientName.setBounds(110, 10, 55, 16);

        jTextFieldClientName.setEditable(false);
        jPanelInfo.add(jTextFieldClientName);
        jTextFieldClientName.setBounds(170, 0, 199, 38);

        jLabelClientAddress.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientAddress.setText("Addresse:");
        jPanelInfo.add(jLabelClientAddress);
        jLabelClientAddress.setBounds(60, 110, 67, 16);

        jTextFieldClientAddress.setEditable(false);
        jPanelInfo.add(jTextFieldClientAddress);
        jTextFieldClientAddress.setBounds(150, 100, 599, 38);

        jLabelClientCity.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientCity.setText("Ville:");
        jPanelInfo.add(jLabelClientCity);
        jLabelClientCity.setBounds(100, 160, 32, 16);

        jTextFieldClientCity.setEditable(false);
        jPanelInfo.add(jTextFieldClientCity);
        jTextFieldClientCity.setBounds(150, 150, 250, 38);

        jTextFieldClientState.setEditable(false);
        jPanelInfo.add(jTextFieldClientState);
        jTextFieldClientState.setBounds(490, 150, 264, 38);

        jLabelClientState.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientState.setText("Province:");
        jPanelInfo.add(jLabelClientState);
        jLabelClientState.setBounds(420, 160, 61, 16);

        jLabelCountry.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelCountry.setText("Pays:");
        jPanelInfo.add(jLabelCountry);
        jLabelCountry.setBounds(100, 190, 34, 45);

        jTextFieldCountry.setEditable(false);
        jPanelInfo.add(jTextFieldCountry);
        jTextFieldCountry.setBounds(150, 200, 248, 38);

        jLabelClientEmail.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientEmail.setText("E-mail:");
        jPanelInfo.add(jLabelClientEmail);
        jLabelClientEmail.setBounds(380, 50, 48, 16);

        jTextFieldClientEmail.setEditable(false);
        jPanelInfo.add(jTextFieldClientEmail);
        jTextFieldClientEmail.setBounds(440, 40, 263, 38);

        jTextFieldClientPhone.setEditable(false);
        jPanelInfo.add(jTextFieldClientPhone);
        jTextFieldClientPhone.setBounds(170, 40, 199, 38);

        jLabelClientPhone.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientPhone.setText("Téléphone:");
        jPanelInfo.add(jLabelClientPhone);
        jLabelClientPhone.setBounds(90, 50, 75, 16);

        jLabelClientLastName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientLastName.setText("Nom:");
        jPanelInfo.add(jLabelClientLastName);
        jLabelClientLastName.setBounds(390, 10, 34, 16);

        jTextFieldClientLastName.setEditable(false);
        jPanelInfo.add(jTextFieldClientLastName);
        jTextFieldClientLastName.setBounds(440, 0, 264, 38);

        jLabelClientZIPCode.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientZIPCode.setText("<html><p align=\"center\">Code</p>Postal:</html>");
        jPanelInfo.add(jLabelClientZIPCode);
        jLabelClientZIPCode.setBounds(440, 190, 43, 45);

        jTextFieldZIPCode.setEditable(false);
        jPanelInfo.add(jTextFieldZIPCode);
        jTextFieldZIPCode.setBounds(490, 200, 264, 38);
        jPanelInfo.add(jSeparatorClientAddress);
        jSeparatorClientAddress.setBounds(6, 237, 1050, 10);
        jPanelInfo.add(jSeparatorClientInfo);
        jSeparatorClientInfo.setBounds(6, 88, 1050, 10);

        jLabelClientDocConfirmation.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientDocConfirmation.setText("Preuve d'addresse:");
        jPanelInfo.add(jLabelClientDocConfirmation);
        jLabelClientDocConfirmation.setBounds(830, 120, 128, 16);

        jTextFieldDocVerification.setEditable(false);
        jPanelInfo.add(jTextFieldDocVerification);
        jTextFieldDocVerification.setBounds(830, 140, 159, 38);

        jCheckBoxValid.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxValid.setText("Validé");
        jCheckBoxValid.setEnabled(false);
        jPanelInfo.add(jCheckBoxValid);
        jCheckBoxValid.setBounds(870, 190, 74, 23);

        jLabelClientCode.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientCode.setText("Code:");
        jPanelInfo.add(jLabelClientCode);
        jLabelClientCode.setBounds(720, 10, 37, 16);

        jTextFieldClientCode.setEditable(false);
        jPanelInfo.add(jTextFieldClientCode);
        jTextFieldClientCode.setBounds(760, 0, 227, 38);

        jButtonInfoReload.setText("Recharger");
        jPanelInfo.add(jButtonInfoReload);
        jButtonInfoReload.setBounds(940, 250, 88, 40);

        jButtonInfoRenew.setText("Renouveler");
        jPanelInfo.add(jButtonInfoRenew);
        jButtonInfoRenew.setBounds(560, 250, 97, 40);

        jButtonInfoCancel.setText("Annuler");
        jPanelInfo.add(jButtonInfoCancel);
        jButtonInfoCancel.setBounds(390, 250, 88, 40);

        jTabbedPane.addTab("Info", jPanelInfo);

        jPanelBooks.setLayout(null);

        jTableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Nom", "Auteur(s)", "Année", "Maison d'édition", "Examplaires"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneBook.setViewportView(jTableBooks);

        jPanelBooks.add(jScrollPaneBook);
        jScrollPaneBook.setBounds(0, 340, 1040, 210);
        jPanelBooks.add(jTextFieldBookSearch);
        jTextFieldBookSearch.setBounds(6, 294, 1040, 40);

        jLabelBookISBN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookISBN.setText("ISBN:");
        jPanelBooks.add(jLabelBookISBN);
        jLabelBookISBN.setBounds(750, 60, 32, 16);

        jLabelBookTitle.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookTitle.setText("Titre:");
        jPanelBooks.add(jLabelBookTitle);
        jLabelBookTitle.setBounds(60, 20, 35, 16);

        jLabelBookAuthors.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookAuthors.setText("Auteur(s):");
        jPanelBooks.add(jLabelBookAuthors);
        jLabelBookAuthors.setBounds(30, 60, 67, 16);

        jLabelBookYear.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookYear.setText("Année:");
        jPanelBooks.add(jLabelBookYear);
        jLabelBookYear.setBounds(740, 20, 47, 16);

        jLabelBookEditor.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookEditor.setText("<html><p align=\"center\">Maison</p>d'édition:<html>");
        jPanelBooks.add(jLabelBookEditor);
        jLabelBookEditor.setBounds(30, 90, 62, 45);

        jLabelTotalSamples.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTotalSamples.setText("<html><p align=\"center\">Quantité</p>d'examplaires:<html>");
        jPanelBooks.add(jLabelTotalSamples);
        jLabelTotalSamples.setBounds(730, 130, 110, 32);

        jTextFieldBookTitle.setEditable(false);
        jPanelBooks.add(jTextFieldBookTitle);
        jTextFieldBookTitle.setBounds(100, 10, 620, 38);

        jTextFieldBookAuthors.setEditable(false);
        jPanelBooks.add(jTextFieldBookAuthors);
        jTextFieldBookAuthors.setBounds(100, 50, 620, 38);

        jTextFieldBookYear.setEditable(false);
        jPanelBooks.add(jTextFieldBookYear);
        jTextFieldBookYear.setBounds(790, 10, 116, 38);

        jTextFieldBookISBN.setEditable(false);
        jPanelBooks.add(jTextFieldBookISBN);
        jTextFieldBookISBN.setBounds(790, 50, 230, 38);

        jTextFieldEditor.setEditable(false);
        jPanelBooks.add(jTextFieldEditor);
        jTextFieldEditor.setBounds(100, 90, 250, 38);

        jTextFieldTotalSamples.setEditable(false);
        jPanelBooks.add(jTextFieldTotalSamples);
        jTextFieldTotalSamples.setBounds(840, 130, 180, 38);

        jCheckBoxRare.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxRare.setText("Rare");
        jCheckBoxRare.setEnabled(false);
        jPanelBooks.add(jCheckBoxRare);
        jCheckBoxRare.setBounds(930, 180, 63, 23);

        jButtonBookReload.setText("Reload");
        jPanelBooks.add(jButtonBookReload);
        jButtonBookReload.setBounds(930, 220, 86, 60);

        jButtonBookReserve.setText("Réserver");
        jPanelBooks.add(jButtonBookReserve);
        jButtonBookReserve.setBounds(470, 220, 97, 60);

        jLabelEditionYear.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelEditionYear.setText("<html><p align=\"center\">Année</p>Édition:<html>");
        jPanelBooks.add(jLabelEditionYear);
        jLabelEditionYear.setBounds(540, 90, 50, 32);

        jTextFieldEditionYear.setEditable(false);
        jPanelBooks.add(jTextFieldEditionYear);
        jTextFieldEditionYear.setBounds(600, 90, 120, 38);

        jLabelBookEdition.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookEdition.setText("Édition:");
        jPanelBooks.add(jLabelBookEdition);
        jLabelBookEdition.setBounds(360, 100, 50, 16);

        jTextFieldBookEdition.setEditable(false);
        jPanelBooks.add(jTextFieldBookEdition);
        jTextFieldBookEdition.setBounds(420, 90, 112, 38);

        jLabelBookFormat.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookFormat.setText("Format:");
        jPanelBooks.add(jLabelBookFormat);
        jLabelBookFormat.setBounds(730, 100, 60, 16);

        jTextFieldBookFormat.setEditable(false);
        jPanelBooks.add(jTextFieldBookFormat);
        jTextFieldBookFormat.setBounds(790, 90, 230, 38);

        jLabelNumberPages.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelNumberPages.setText("<html><p align=\"center\">Nombre</p>Pages:<html>");
        jPanelBooks.add(jLabelNumberPages);
        jLabelNumberPages.setBounds(40, 130, 60, 32);

        jTextFieldNumberPages.setEditable(false);
        jPanelBooks.add(jTextFieldNumberPages);
        jTextFieldNumberPages.setBounds(100, 130, 150, 38);

        jLabelOriginalLanguage.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelOriginalLanguage.setText("<html><p align=\"center\">Langue</p>Originelle:<html>");
        jPanelBooks.add(jLabelOriginalLanguage);
        jLabelOriginalLanguage.setBounds(260, 130, 70, 32);

        jTextFieldOriginalLanguage.setEditable(false);
        jPanelBooks.add(jTextFieldOriginalLanguage);
        jTextFieldOriginalLanguage.setBounds(330, 130, 150, 38);

        jLabelEditionLanguage.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelEditionLanguage.setText("<html><p align=\"center\">Langue</p>Édition:<html>");
        jPanelBooks.add(jLabelEditionLanguage);
        jLabelEditionLanguage.setBounds(500, 130, 70, 32);

        jTextFieldEditionLanguage.setEditable(false);
        jPanelBooks.add(jTextFieldEditionLanguage);
        jTextFieldEditionLanguage.setBounds(570, 130, 150, 38);

        jTabbedPane.addTab("Livres", jPanelBooks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1072, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookReload;
    private javax.swing.JButton jButtonBookReserve;
    private javax.swing.JButton jButtonInfoCancel;
    private javax.swing.JButton jButtonInfoReload;
    private javax.swing.JButton jButtonInfoRenew;
    private javax.swing.JCheckBox jCheckBoxRare;
    private javax.swing.JCheckBox jCheckBoxValid;
    private javax.swing.JLabel jLabelBookAuthors;
    private javax.swing.JLabel jLabelBookEdition;
    private javax.swing.JLabel jLabelBookEditor;
    private javax.swing.JLabel jLabelBookFormat;
    private javax.swing.JLabel jLabelBookISBN;
    private javax.swing.JLabel jLabelBookTitle;
    private javax.swing.JLabel jLabelBookYear;
    private javax.swing.JLabel jLabelClientAddress;
    private javax.swing.JLabel jLabelClientCity;
    private javax.swing.JLabel jLabelClientCode;
    private javax.swing.JLabel jLabelClientDocConfirmation;
    private javax.swing.JLabel jLabelClientEmail;
    private javax.swing.JLabel jLabelClientLastName;
    private javax.swing.JLabel jLabelClientName;
    private javax.swing.JLabel jLabelClientPhone;
    private javax.swing.JLabel jLabelClientState;
    private javax.swing.JLabel jLabelClientZIPCode;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelEditionLanguage;
    private javax.swing.JLabel jLabelEditionYear;
    private javax.swing.JLabel jLabelNumberPages;
    private javax.swing.JLabel jLabelOriginalLanguage;
    private javax.swing.JLabel jLabelTotalSamples;
    private javax.swing.JPanel jPanelBooks;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JScrollPane jScrollPaneBook;
    private javax.swing.JScrollPane jScrollPaneReservation;
    private javax.swing.JSeparator jSeparatorClientAddress;
    private javax.swing.JSeparator jSeparatorClientInfo;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableBooks;
    private javax.swing.JTable jTableReservations;
    private javax.swing.JTextField jTextFieldBookAuthors;
    private javax.swing.JTextField jTextFieldBookEdition;
    private javax.swing.JTextField jTextFieldBookFormat;
    private javax.swing.JTextField jTextFieldBookISBN;
    private javax.swing.JTextField jTextFieldBookSearch;
    private javax.swing.JTextField jTextFieldBookTitle;
    private javax.swing.JTextField jTextFieldBookYear;
    private javax.swing.JTextField jTextFieldClientAddress;
    private javax.swing.JTextField jTextFieldClientCity;
    private javax.swing.JTextField jTextFieldClientCode;
    private javax.swing.JTextField jTextFieldClientEmail;
    private javax.swing.JTextField jTextFieldClientLastName;
    private javax.swing.JTextField jTextFieldClientName;
    private javax.swing.JTextField jTextFieldClientPhone;
    private javax.swing.JTextField jTextFieldClientSearch;
    private javax.swing.JTextField jTextFieldClientState;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldDocVerification;
    private javax.swing.JTextField jTextFieldEditionLanguage;
    private javax.swing.JTextField jTextFieldEditionYear;
    private javax.swing.JTextField jTextFieldEditor;
    private javax.swing.JTextField jTextFieldNumberPages;
    private javax.swing.JTextField jTextFieldOriginalLanguage;
    private javax.swing.JTextField jTextFieldTotalSamples;
    private javax.swing.JTextField jTextFieldZIPCode;
    // End of variables declaration//GEN-END:variables

    //JTABLE
    private void configureTables() {
        jTableBooks.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTableBooks.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableBooks.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableBooks.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableBooks.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableBooks.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableBooks.getColumnModel().getColumn(5).setPreferredWidth(100);

        jTableReservations.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTableReservations.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableReservations.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableReservations.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableReservations.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableReservations.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableReservations.getColumnModel().getColumn(5).setPreferredWidth(100);
    }

    // BOOK TABLE
    public Integer actualBookSelected = null;

    public void updateBookTable(Set<Book> bookSet) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableBooks.getModel();
        int size = defaultTableModel.getRowCount();
        for (int i = 0; i < size; i++) {
            defaultTableModel.removeRow(0);
        }

        if (!bookSet.isEmpty()) {
            bookSet.stream().map((book) -> {
                BookEdition bookEdition = (BookEdition) book;
                Object[] obj = new Object[6];
                obj[0] = bookEdition.getISBN();
                obj[1] = bookEdition.getTitle();
                Set<Author> authors = bookEdition.getAuthors();
                if(authors != null && !authors.isEmpty()) {
                    List<String> list = new ArrayList<>();
                    authors.forEach(author -> {
                        list.add(author.getName());
                    });
                    obj[2] = String.join(",", list);
                } else {
                    obj[2] = "";
                }
                obj[3] = bookEdition.getBookYear();
                obj[4] = bookEdition.getPublisher().getName();
                obj[5] = bookEdition.getTotalSamples();

                return obj;
            }).forEachOrdered((obj) -> {
                defaultTableModel.addRow(obj);
            });

            actualBookSelected = 0;
            jTableBooks.setRowSelectionInterval(0, actualBookSelected);
        }
    }

    public void setBookFields(Book book) {
        if (book != null) {
            BookEdition bookEdition = (BookSample) book;
            jTextFieldBookTitle.setText(bookEdition.getTitle());
            jTextFieldBookYear.setText(String.valueOf(bookEdition.getBookYear()));

            Set<Author> authors = bookEdition.getAuthors();
            if(authors != null && !authors.isEmpty()) {
                List<String> list = new ArrayList<>();
                authors.forEach(author -> {
                    list.add(author.getName());
                });
                jTextFieldBookAuthors.setText(String.join(",", list));
            } else {
                jTextFieldBookAuthors.setText("");
            }

            jTextFieldBookISBN.setText(bookEdition.getISBN());
            jTextFieldEditor.setText(bookEdition.getPublisher().getName());
            jTextFieldBookEdition.setText(bookEdition.getEdition());
            jTextFieldEditionYear.setText(String.valueOf(bookEdition.getEditionYear()));
            jTextFieldBookFormat.setText(bookEdition.getFormat());
            jTextFieldNumberPages.setText(String.valueOf(bookEdition.getTotalPages()));
            jTextFieldTotalSamples.setText(String.valueOf(bookEdition.getTotalSamples()));
            jTextFieldOriginalLanguage.setText(bookEdition.getOriginalLanguage());
            jTextFieldEditionLanguage.setText(bookEdition.getEditionLanguage());
            jCheckBoxRare.setSelected(bookEdition.isRare());
        }
    }
    // BOOK TABLE

    // RESERVATION TABLE
    public Integer actualReservationSelected = null;

    public void updateReservationTable(Set<BookReservation> bookReservationSet) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableReservations.getModel();
        int size = defaultTableModel.getRowCount();
        for (int i = 0; i < size; i++) {
            defaultTableModel.removeRow(0);
        }

        if (!bookReservationSet.isEmpty()) {
            bookReservationSet.stream().map((bookReservation) -> {
                Object[] obj = new Object[7];
                obj[0] = bookReservation.getIdBookReservation();
                obj[1] = bookReservation.getClient().getCode();
                obj[2] = bookReservation.getBookSample().getISBN();
                obj[3] = bookReservation.getBookSample().getTitle();
                obj[4] = bookReservation.getCreationDate();
                obj[5] = bookReservation.getReservationStatus().getStatus();
                obj[6] = "LIVRE NON RARE";
                return obj;
            }).forEachOrdered((obj) -> {
                defaultTableModel.addRow(obj);
            });

            actualReservationSelected = 0;
            jTableReservations.setRowSelectionInterval(0, actualReservationSelected);
        }
    }
    // RESERVATION TABLE

    public JButton getjButtonBookReserve() {
        return jButtonBookReserve;
    }

    public JButton getjButtonInfoCancel() {
        return jButtonInfoCancel;
    }

    public JButton getjButtonInfoRenew() {
        return jButtonInfoRenew;
    }

    public JCheckBox getjCheckBoxRare() {
        return jCheckBoxRare;
    }

    public JCheckBox getjCheckBoxValid() {
        return jCheckBoxValid;
    }

    public JTextField getjTextFieldBookAuthors() {
        return jTextFieldBookAuthors;
    }

    public JTextField getjTextFieldBookEdition() {
        return jTextFieldBookEdition;
    }

    public JTextField getjTextFieldBookFormat() {
        return jTextFieldBookFormat;
    }

    public JTextField getjTextFieldBookISBN() {
        return jTextFieldBookISBN;
    }

    public JTextField getjTextFieldBookSearch() {
        return jTextFieldBookSearch;
    }

    public JTextField getjTextFieldBookTitle() {
        return jTextFieldBookTitle;
    }

    public JTextField getjTextFieldBookYear() {
        return jTextFieldBookYear;
    }

    public JTextField getjTextFieldClientAddress() {
        return jTextFieldClientAddress;
    }

    public JTextField getjTextFieldClientCity() {
        return jTextFieldClientCity;
    }

    public JTextField getjTextFieldClientCode() {
        return jTextFieldClientCode;
    }

    public JTextField getjTextFieldClientEmail() {
        return jTextFieldClientEmail;
    }

    public JTextField getjTextFieldClientLastName() {
        return jTextFieldClientLastName;
    }

    public JTextField getjTextFieldClientName() {
        return jTextFieldClientName;
    }

    public JTextField getjTextFieldClientPhone() {
        return jTextFieldClientPhone;
    }

    public JTextField getjTextFieldClientSearch() {
        return jTextFieldClientSearch;
    }

    public JTextField getjTextFieldClientState() {
        return jTextFieldClientState;
    }

    public JTextField getjTextFieldCountry() {
        return jTextFieldCountry;
    }

    public JTextField getjTextFieldDocVerification() {
        return jTextFieldDocVerification;
    }

    public JTextField getjTextFieldEditionLanguage() {
        return jTextFieldEditionLanguage;
    }

    public JTextField getjTextFieldEditionYear() {
        return jTextFieldEditionYear;
    }

    public JTextField getjTextFieldEditor() {
        return jTextFieldEditor;
    }

    public JTextField getjTextFieldNumberPages() {
        return jTextFieldNumberPages;
    }

    public JTextField getjTextFieldOriginalLanguage() {
        return jTextFieldOriginalLanguage;
    }

    public JTextField getjTextFieldTotalSamples() {
        return jTextFieldTotalSamples;
    }

    public JTextField getjTextFieldZIPCode() {
        return jTextFieldZIPCode;
    }

    public JTable getjTableBooks() {
        return jTableBooks;
    }

    public JTable getjTableReservations() {
        return jTableReservations;
    }
    
    public JButton getjButtonInfoReload() {
        return jButtonInfoReload;
    }
    
    public JButton getjButtonBookReload() {
        return jButtonBookReload;
    }
    
}
