/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grasset.view;

import javax.swing.*;
import java.awt.event.KeyEvent;

public class LoginJPanelView extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanelView
     */
    public LoginJPanelView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUserCode = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUserCode = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelRecoverPassword = new javax.swing.JLabel();
        jButtonConnect = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 24))); // NOI18N
        setBounds(new java.awt.Rectangle(0, 0, 400, 255));
        setMaximumSize(new java.awt.Dimension(400, 255));
        setPreferredSize(new java.awt.Dimension(400, 255));

        jLabelUserCode.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelUserCode.setText("Cod. Utilisateur: ");

        jLabelPassword.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelPassword.setText("Mot de Passe: ");

        jLabelRecoverPassword.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelRecoverPassword.setText("J'ai oublié mon mot de passe.");

        jButtonConnect.setText("Connecter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUserCode)
                    .addComponent(jLabelPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldUserCode)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabelRecoverPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButtonConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserCode)
                    .addComponent(jTextFieldUserCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelPassword)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jButtonConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecoverPassword)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRecoverPassword;
    private javax.swing.JLabel jLabelUserCode;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUserCode;
    // End of variables declaration//GEN-END:variables

    // Getters & Setters
    public JButton getjButtonConnect() {
        return jButtonConnect;
    }

    public JPasswordField getjPasswordField() {
        return jPasswordField;
    }

    public JTextField getjTextFieldUserCode() {
        return jTextFieldUserCode;
    }

    
    
}
