/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grasset.view;

import java.awt.Dimension;
import java.awt.GridBagLayout;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author henrique
 */
public class MainJFrameView extends JFrame {

    private final JPanel content;

    /**
     * Creates new form MainJFrameView
     */
    public MainJFrameView() {               
        setTitle("Bibliotèque Marguerite Bourgeoys");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        content = new JPanel(new GridBagLayout());

        initComponents();
    }

    public void addPanel(JPanel jpanel) {
        remove(content);
        content.removeAll();

        content.setLayout(new BoxLayout(content, BoxLayout.X_AXIS));
        content.add(Box.createHorizontalGlue());
        content.add(jpanel);
        content.add(Box.createHorizontalGlue());

        setMaximumSize(new Dimension(jpanel.getMaximumSize().width + 50, jpanel.getMaximumSize().height + 50));
        setMinimumSize(new Dimension(jpanel.getMinimumSize().width + 50, jpanel.getMinimumSize().height + 50));

        setSize(jpanel.getSize());

        Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screenSize.width - getWidth()) / 2, (screenSize.height - getHeight()) / 2);

        setContentPane(content);
    }

    public void setLookAndFeel() {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jMenuAccount.setText("Compte");

        jMenuItemLogout.setText("Quitter");
        jMenuAccount.add(jMenuItemLogout);

        jMenuBar.add(jMenuAccount);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemLogout;
    // End of variables declaration//GEN-END:variables

    public JMenu getjMenuAccount() {
        return jMenuAccount;
    }

    public JMenuBar getjMenuBar() {
        return jMenuBar;
    }

    public JMenuItem getjMenuItemLogout() {
        return jMenuItemLogout;
    }



}
