/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grasset.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author henrique
 */
public class ManagerJPanelView extends javax.swing.JPanel {

    /**
     * Creates new form ManagerJPanelView
     */
    public ManagerJPanelView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelBooks = new javax.swing.JPanel();
        jScrollPaneBook = new javax.swing.JScrollPane();
        jTableBooks = new javax.swing.JTable();
        jTextFieldBookSearch = new javax.swing.JTextField();
        jLabelBookISBN = new javax.swing.JLabel();
        jLabelBookTitle = new javax.swing.JLabel();
        jLabelBookAuthors = new javax.swing.JLabel();
        jLabelBookYear = new javax.swing.JLabel();
        jLabelBookEditor = new javax.swing.JLabel();
        jLabelTotalSamples = new javax.swing.JLabel();
        jLabelPenalityPrice = new javax.swing.JLabel();
        jTextFieldBookTitle = new javax.swing.JTextField();
        jTextFieldBookAuthors = new javax.swing.JTextField();
        jTextFieldBookYear = new javax.swing.JTextField();
        jTextFieldBookISBN = new javax.swing.JTextField();
        jTextFieldEditor = new javax.swing.JTextField();
        jTextFieldPenalityPrice = new javax.swing.JTextField();
        jTextFieldTotalSamples = new javax.swing.JTextField();
        jCheckBoxBookRare = new javax.swing.JCheckBox();
        jButtonBookSave = new javax.swing.JButton();
        jButtonBookDelete = new javax.swing.JButton();
        jButtonBookDetails = new javax.swing.JButton();
        jButtonBookReserve = new javax.swing.JButton();
        jButtonBookClear = new javax.swing.JButton();
        jLabelEditionYear = new javax.swing.JLabel();
        jTextFieldEditionYear = new javax.swing.JTextField();
        jLabelBookEdition = new javax.swing.JLabel();
        jTextFieldBookEdition = new javax.swing.JTextField();
        jLabelBookFormat = new javax.swing.JLabel();
        jTextFieldBookFormat = new javax.swing.JTextField();
        jLabelNumberPages = new javax.swing.JLabel();
        jTextFieldNumberPages = new javax.swing.JTextField();
        jLabelBookPrice = new javax.swing.JLabel();
        jTextFieldBookPrice = new javax.swing.JTextField();
        jLabelOriginalLanguage = new javax.swing.JLabel();
        jTextFieldOriginalLanguage = new javax.swing.JTextField();
        jLabelEditionLanguage = new javax.swing.JLabel();
        jTextFieldEditionLanguage = new javax.swing.JTextField();
        jLabelSampleCode = new javax.swing.JLabel();
        jTextFieldSampleCode = new javax.swing.JTextField();
        jPanelClients = new javax.swing.JPanel();
        jScrollPaneClient = new javax.swing.JScrollPane();
        jTableClients = new javax.swing.JTable();
        jTextFieldClientSearch = new javax.swing.JTextField();
        jLabelClientName = new javax.swing.JLabel();
        jTextFieldClientName = new javax.swing.JTextField();
        jLabelClientAddress = new javax.swing.JLabel();
        jTextFieldClientAddress = new javax.swing.JTextField();
        jLabelClientCity = new javax.swing.JLabel();
        jTextFieldClientCity = new javax.swing.JTextField();
        jTextFieldClientState = new javax.swing.JTextField();
        jLabelClientState = new javax.swing.JLabel();
        jLabelCountry = new javax.swing.JLabel();
        jTextFieldCountry = new javax.swing.JTextField();
        jLabelClientEmail = new javax.swing.JLabel();
        jTextFieldClientEmail = new javax.swing.JTextField();
        jTextFieldClientPhone = new javax.swing.JTextField();
        jLabelClientPhone = new javax.swing.JLabel();
        jLabelClientLastName = new javax.swing.JLabel();
        jTextFieldClientLastName = new javax.swing.JTextField();
        jLabelClientZIPCode = new javax.swing.JLabel();
        jTextFieldZIPCode = new javax.swing.JTextField();
        jSeparatorClientAddress = new javax.swing.JSeparator();
        jSeparatorClientInfo = new javax.swing.JSeparator();
        jLabelClientDocConfirmation = new javax.swing.JLabel();
        jTextFieldDocVerification = new javax.swing.JTextField();
        jCheckBoxClientValid = new javax.swing.JCheckBox();
        jLabelClientId = new javax.swing.JLabel();
        jTextFieldClientId = new javax.swing.JTextField();
        jLabelClientCode = new javax.swing.JLabel();
        jTextFieldClientCode = new javax.swing.JTextField();
        jButtonClientSave = new javax.swing.JButton();
        jButtonClientDelete = new javax.swing.JButton();
        jButtonClientDetails = new javax.swing.JButton();
        jButtonClientReserve = new javax.swing.JButton();
        jButtonClientClear = new javax.swing.JButton();
        jPanelReservations = new javax.swing.JPanel();
        jScrollPaneReservations = new javax.swing.JScrollPane();
        jTableReservations = new javax.swing.JTable();
        jTextFieldReservationSearch = new javax.swing.JTextField();
        jLabelReservationBookName = new javax.swing.JLabel();
        jTextFieldReservationBookName = new javax.swing.JTextField();
        jLabelReservationBookISBN = new javax.swing.JLabel();
        jTextFieldReservationBookISBN = new javax.swing.JTextField();
        jTextFieldReservationClientCode = new javax.swing.JTextField();
        jLabelReservationClientCode = new javax.swing.JLabel();
        jTextFieldReservationClientName = new javax.swing.JTextField();
        jLabelReservationClientName = new javax.swing.JLabel();
        jTextFieldReservationDate = new javax.swing.JTextField();
        jLabelReservationDate = new javax.swing.JLabel();
        jLabelReservationReturnDate = new javax.swing.JLabel();
        jTextFieldReservationReturnDate = new javax.swing.JTextField();
        jLabelReservationStatus = new javax.swing.JLabel();
        jTextFieldReservationStatus = new javax.swing.JTextField();
        jCheckBoxReservationRare = new javax.swing.JCheckBox();
        jSeparatorReservationClient = new javax.swing.JSeparator();
        jSeparatorReservationBook = new javax.swing.JSeparator();
        jButtonReservationFinish = new javax.swing.JButton();
        jButtonReservationCancel = new javax.swing.JButton();
        jButtonReservationRenew = new javax.swing.JButton();
        jButtonReservationClear = new javax.swing.JButton();
        jLabelReservationBookCodeSample = new javax.swing.JLabel();
        jTextFieldReservationBookCodeSample = new javax.swing.JTextField();
        jPanelReservation = new javax.swing.JPanel();

        jPanelBooks.setLayout(null);

        jTableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Nom", "Auteur(s)", "Année", "Maison d'édition", "Examplaires"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneBook.setViewportView(jTableBooks);

        jPanelBooks.add(jScrollPaneBook);
        jScrollPaneBook.setBounds(0, 340, 1060, 210);
        jPanelBooks.add(jTextFieldBookSearch);
        jTextFieldBookSearch.setBounds(6, 294, 1040, 40);

        jLabelBookISBN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookISBN.setText("ISBN:");
        jPanelBooks.add(jLabelBookISBN);
        jLabelBookISBN.setBounds(750, 60, 32, 16);

        jLabelBookTitle.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookTitle.setText("Titre:");
        jPanelBooks.add(jLabelBookTitle);
        jLabelBookTitle.setBounds(60, 20, 35, 16);

        jLabelBookAuthors.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookAuthors.setText("Auteur(s):");
        jPanelBooks.add(jLabelBookAuthors);
        jLabelBookAuthors.setBounds(30, 60, 67, 16);

        jLabelBookYear.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookYear.setText("Année:");
        jPanelBooks.add(jLabelBookYear);
        jLabelBookYear.setBounds(740, 20, 47, 16);

        jLabelBookEditor.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookEditor.setText("<html><p align=\"center\">Maison</p>d'édition:<html>");
        jPanelBooks.add(jLabelBookEditor);
        jLabelBookEditor.setBounds(30, 90, 62, 45);

        jLabelTotalSamples.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTotalSamples.setText("<html><p align=\"center\">Quantité</p>d'examplaires:<html>");
        jPanelBooks.add(jLabelTotalSamples);
        jLabelTotalSamples.setBounds(730, 130, 110, 32);

        jLabelPenalityPrice.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelPenalityPrice.setText("<html><p align=\"center\">Prix </p>d'amande:<html>");
        jPanelBooks.add(jLabelPenalityPrice);
        jLabelPenalityPrice.setBounds(280, 130, 70, 32);
        jPanelBooks.add(jTextFieldBookTitle);
        jTextFieldBookTitle.setBounds(100, 10, 620, 38);
        jPanelBooks.add(jTextFieldBookAuthors);
        jTextFieldBookAuthors.setBounds(100, 50, 620, 38);
        jPanelBooks.add(jTextFieldBookYear);
        jTextFieldBookYear.setBounds(790, 10, 116, 38);
        jPanelBooks.add(jTextFieldBookISBN);
        jTextFieldBookISBN.setBounds(790, 50, 230, 38);
        jPanelBooks.add(jTextFieldEditor);
        jTextFieldEditor.setBounds(100, 90, 250, 38);
        jPanelBooks.add(jTextFieldPenalityPrice);
        jTextFieldPenalityPrice.setBounds(360, 130, 140, 38);
        jPanelBooks.add(jTextFieldTotalSamples);
        jTextFieldTotalSamples.setBounds(840, 130, 180, 38);

        jCheckBoxBookRare.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxBookRare.setText("Rare");
        jPanelBooks.add(jCheckBoxBookRare);
        jCheckBoxBookRare.setBounds(930, 180, 63, 23);

        jButtonBookSave.setText("Enregistrer");
        jPanelBooks.add(jButtonBookSave);
        jButtonBookSave.setBounds(210, 220, 112, 60);

        jButtonBookDelete.setText("Supprimer");
        jPanelBooks.add(jButtonBookDelete);
        jButtonBookDelete.setBounds(340, 220, 108, 60);

        jButtonBookDetails.setText("Détails");
        jPanelBooks.add(jButtonBookDetails);
        jButtonBookDetails.setBounds(470, 220, 88, 60);

        jButtonBookReserve.setText("Réserver");
        jPanelBooks.add(jButtonBookReserve);
        jButtonBookReserve.setBounds(580, 220, 97, 60);

        jButtonBookClear.setText("Nettoyer");
        jPanelBooks.add(jButtonBookClear);
        jButtonBookClear.setBounds(690, 220, 98, 60);

        jLabelEditionYear.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelEditionYear.setText("<html><p align=\"center\">Année</p>Édition:<html>");
        jPanelBooks.add(jLabelEditionYear);
        jLabelEditionYear.setBounds(540, 90, 50, 32);
        jPanelBooks.add(jTextFieldEditionYear);
        jTextFieldEditionYear.setBounds(600, 90, 120, 38);

        jLabelBookEdition.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookEdition.setText("Édition:");
        jPanelBooks.add(jLabelBookEdition);
        jLabelBookEdition.setBounds(360, 100, 50, 16);
        jPanelBooks.add(jTextFieldBookEdition);
        jTextFieldBookEdition.setBounds(420, 90, 112, 38);

        jLabelBookFormat.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookFormat.setText("Format:");
        jPanelBooks.add(jLabelBookFormat);
        jLabelBookFormat.setBounds(730, 100, 60, 16);
        jPanelBooks.add(jTextFieldBookFormat);
        jTextFieldBookFormat.setBounds(790, 90, 230, 38);

        jLabelNumberPages.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelNumberPages.setText("<html><p align=\"center\">Nombre</p>Pages:<html>");
        jPanelBooks.add(jLabelNumberPages);
        jLabelNumberPages.setBounds(40, 130, 60, 32);
        jPanelBooks.add(jTextFieldNumberPages);
        jTextFieldNumberPages.setBounds(100, 130, 150, 38);

        jLabelBookPrice.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelBookPrice.setText("<html><p align=\"center\">Prix </p>du Livre:<html>");
        jPanelBooks.add(jLabelBookPrice);
        jLabelBookPrice.setBounds(530, 130, 70, 32);
        jPanelBooks.add(jTextFieldBookPrice);
        jTextFieldBookPrice.setBounds(600, 130, 120, 38);

        jLabelOriginalLanguage.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelOriginalLanguage.setText("<html><p align=\"center\">Langue</p>Originelle:<html>");
        jPanelBooks.add(jLabelOriginalLanguage);
        jLabelOriginalLanguage.setBounds(30, 170, 70, 32);
        jPanelBooks.add(jTextFieldOriginalLanguage);
        jTextFieldOriginalLanguage.setBounds(100, 170, 150, 38);

        jLabelEditionLanguage.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelEditionLanguage.setText("<html><p align=\"center\">Langue</p>Édition:<html>");
        jPanelBooks.add(jLabelEditionLanguage);
        jLabelEditionLanguage.setBounds(310, 170, 70, 32);
        jPanelBooks.add(jTextFieldEditionLanguage);
        jTextFieldEditionLanguage.setBounds(380, 170, 150, 38);

        jLabelSampleCode.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelSampleCode.setText("<html><p align=\"center\">Code</p>d'examplaire:<html>");
        jPanelBooks.add(jLabelSampleCode);
        jLabelSampleCode.setBounds(580, 170, 110, 32);
        jPanelBooks.add(jTextFieldSampleCode);
        jTextFieldSampleCode.setBounds(690, 170, 180, 38);

        jTabbedPane.addTab("Livres", jPanelBooks);

        jPanelClients.setLayout(null);

        jTableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Id", "Prénom", "Nom", "E-mail", "Téléphone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneClient.setViewportView(jTableClients);

        jPanelClients.add(jScrollPaneClient);
        jScrollPaneClient.setBounds(0, 340, 1056, 210);
        jPanelClients.add(jTextFieldClientSearch);
        jTextFieldClientSearch.setBounds(6, 294, 1050, 40);

        jLabelClientName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientName.setText("Prénom:");
        jPanelClients.add(jLabelClientName);
        jLabelClientName.setBounds(110, 10, 55, 16);
        jPanelClients.add(jTextFieldClientName);
        jTextFieldClientName.setBounds(170, 0, 199, 38);

        jLabelClientAddress.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientAddress.setText("Addresse:");
        jPanelClients.add(jLabelClientAddress);
        jLabelClientAddress.setBounds(60, 110, 67, 16);
        jPanelClients.add(jTextFieldClientAddress);
        jTextFieldClientAddress.setBounds(150, 100, 599, 38);

        jLabelClientCity.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientCity.setText("Ville:");
        jPanelClients.add(jLabelClientCity);
        jLabelClientCity.setBounds(100, 160, 32, 16);
        jPanelClients.add(jTextFieldClientCity);
        jTextFieldClientCity.setBounds(150, 150, 250, 38);
        jPanelClients.add(jTextFieldClientState);
        jTextFieldClientState.setBounds(490, 150, 264, 38);

        jLabelClientState.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientState.setText("Province:");
        jPanelClients.add(jLabelClientState);
        jLabelClientState.setBounds(420, 160, 61, 16);

        jLabelCountry.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelCountry.setText("Pays:");
        jPanelClients.add(jLabelCountry);
        jLabelCountry.setBounds(100, 190, 34, 45);
        jPanelClients.add(jTextFieldCountry);
        jTextFieldCountry.setBounds(150, 200, 248, 38);

        jLabelClientEmail.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientEmail.setText("E-mail:");
        jPanelClients.add(jLabelClientEmail);
        jLabelClientEmail.setBounds(390, 50, 48, 16);
        jPanelClients.add(jTextFieldClientEmail);
        jTextFieldClientEmail.setBounds(440, 40, 263, 38);
        jPanelClients.add(jTextFieldClientPhone);
        jTextFieldClientPhone.setBounds(170, 40, 199, 38);

        jLabelClientPhone.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientPhone.setText("Téléphone:");
        jPanelClients.add(jLabelClientPhone);
        jLabelClientPhone.setBounds(90, 50, 75, 16);

        jLabelClientLastName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientLastName.setText("Nom:");
        jPanelClients.add(jLabelClientLastName);
        jLabelClientLastName.setBounds(390, 10, 34, 16);
        jPanelClients.add(jTextFieldClientLastName);
        jTextFieldClientLastName.setBounds(440, 0, 264, 38);

        jLabelClientZIPCode.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientZIPCode.setText("<html><p align=\"center\">Code</p>Postal:</html>");
        jPanelClients.add(jLabelClientZIPCode);
        jLabelClientZIPCode.setBounds(440, 190, 43, 45);
        jPanelClients.add(jTextFieldZIPCode);
        jTextFieldZIPCode.setBounds(490, 200, 264, 38);
        jPanelClients.add(jSeparatorClientAddress);
        jSeparatorClientAddress.setBounds(6, 237, 1050, 10);
        jPanelClients.add(jSeparatorClientInfo);
        jSeparatorClientInfo.setBounds(6, 88, 1050, 10);

        jLabelClientDocConfirmation.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientDocConfirmation.setText("Preuve d'addresse:");
        jPanelClients.add(jLabelClientDocConfirmation);
        jLabelClientDocConfirmation.setBounds(830, 120, 128, 16);
        jPanelClients.add(jTextFieldDocVerification);
        jTextFieldDocVerification.setBounds(830, 140, 159, 38);

        jCheckBoxClientValid.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jCheckBoxClientValid.setText("Validé");
        jPanelClients.add(jCheckBoxClientValid);
        jCheckBoxClientValid.setBounds(870, 190, 74, 23);

        jLabelClientId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientId.setText("Id:");
        jPanelClients.add(jLabelClientId);
        jLabelClientId.setBounds(740, 10, 16, 16);
        jPanelClients.add(jTextFieldClientId);
        jTextFieldClientId.setBounds(760, 0, 227, 38);

        jLabelClientCode.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelClientCode.setText("Code:");
        jPanelClients.add(jLabelClientCode);
        jLabelClientCode.setBounds(720, 50, 37, 16);
        jPanelClients.add(jTextFieldClientCode);
        jTextFieldClientCode.setBounds(760, 40, 227, 38);

        jButtonClientSave.setText("Enregistrer");
        jPanelClients.add(jButtonClientSave);
        jButtonClientSave.setBounds(160, 250, 112, 40);

        jButtonClientDelete.setText("Supprimer");
        jPanelClients.add(jButtonClientDelete);
        jButtonClientDelete.setBounds(320, 249, 108, 40);

        jButtonClientDetails.setText("Détails");
        jPanelClients.add(jButtonClientDetails);
        jButtonClientDetails.setBounds(470, 249, 88, 40);

        jButtonClientReserve.setText("Réserver");
        jPanelClients.add(jButtonClientReserve);
        jButtonClientReserve.setBounds(610, 249, 97, 40);

        jButtonClientClear.setText("Nettoyer");
        jPanelClients.add(jButtonClientClear);
        jButtonClientClear.setBounds(760, 249, 98, 40);

        jTabbedPane.addTab("Clients", jPanelClients);

        jPanelReservations.setLayout(null);

        jTableReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Nom du Livre", "Code Client", "Nom Client", "Date du Prêt", "Prévision"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneReservations.setViewportView(jTableReservations);

        jPanelReservations.add(jScrollPaneReservations);
        jScrollPaneReservations.setBounds(0, 340, 1062, 210);
        jPanelReservations.add(jTextFieldReservationSearch);
        jTextFieldReservationSearch.setBounds(6, 294, 1040, 40);

        jLabelReservationBookName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelReservationBookName.setText("Titre:");
        jPanelReservations.add(jLabelReservationBookName);
        jLabelReservationBookName.setBounds(300, 20, 40, 16);
        jPanelReservations.add(jTextFieldReservationBookName);
        jTextFieldReservationBookName.setBounds(340, 10, 264, 38);

        jLabelReservationBookISBN.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelReservationBookISBN.setText("ISBN:");
        jPanelReservations.add(jLabelReservationBookISBN);
        jLabelReservationBookISBN.setBounds(20, 20, 32, 16);
        jPanelReservations.add(jTextFieldReservationBookISBN);
        jTextFieldReservationBookISBN.setBounds(60, 10, 220, 38);
        jPanelReservations.add(jTextFieldReservationClientCode);
        jTextFieldReservationClientCode.setBounds(60, 80, 220, 38);

        jLabelReservationClientCode.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelReservationClientCode.setText("<html><p align=\"center\">Code</p>Client:</html>");
        jPanelReservations.add(jLabelReservationClientCode);
        jLabelReservationClientCode.setBounds(10, 80, 42, 32);
        jPanelReservations.add(jTextFieldReservationClientName);
        jTextFieldReservationClientName.setBounds(350, 80, 250, 38);

        jLabelReservationClientName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelReservationClientName.setText("<html><p align=\"center\">Nom</p>Client:</html>");
        jPanelReservations.add(jLabelReservationClientName);
        jLabelReservationClientName.setBounds(300, 80, 60, 32);
        jPanelReservations.add(jTextFieldReservationDate);
        jTextFieldReservationDate.setBounds(160, 160, 170, 38);

        jLabelReservationDate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelReservationDate.setText("<html><p align=\"center\">Date</p>du Prêt:</html>");
        jPanelReservations.add(jLabelReservationDate);
        jLabelReservationDate.setBounds(100, 160, 52, 32);

        jLabelReservationReturnDate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelReservationReturnDate.setText("<html><p align=\"center\">Prévision</p>de Retur:</html>");
        jPanelReservations.add(jLabelReservationReturnDate);
        jLabelReservationReturnDate.setBounds(350, 160, 62, 32);
        jPanelReservations.add(jTextFieldReservationReturnDate);
        jTextFieldReservationReturnDate.setBounds(420, 160, 180, 38);

        jLabelReservationStatus.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelReservationStatus.setText("<html><p align=\"center\">Status</p>Réservation:</html>");
        jPanelReservations.add(jLabelReservationStatus);
        jLabelReservationStatus.setBounds(620, 160, 83, 32);
        jPanelReservations.add(jTextFieldReservationStatus);
        jTextFieldReservationStatus.setBounds(710, 160, 264, 38);

        jCheckBoxReservationRare.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jCheckBoxReservationRare.setText("Rare");
        jPanelReservations.add(jCheckBoxReservationRare);
        jCheckBoxReservationRare.setBounds(940, 20, 64, 23);
        jPanelReservations.add(jSeparatorReservationClient);
        jSeparatorReservationClient.setBounds(10, 60, 1046, 12);
        jPanelReservations.add(jSeparatorReservationBook);
        jSeparatorReservationBook.setBounds(10, 140, 1046, 12);

        jButtonReservationFinish.setText("Conclure");
        jPanelReservations.add(jButtonReservationFinish);
        jButtonReservationFinish.setBounds(290, 230, 100, 60);

        jButtonReservationCancel.setText("Canceler");
        jPanelReservations.add(jButtonReservationCancel);
        jButtonReservationCancel.setBounds(410, 230, 98, 60);

        jButtonReservationRenew.setText("Renouveler");
        jPanelReservations.add(jButtonReservationRenew);
        jButtonReservationRenew.setBounds(530, 230, 113, 60);

        jButtonReservationClear.setText("Nettoyer");
        jPanelReservations.add(jButtonReservationClear);
        jButtonReservationClear.setBounds(660, 230, 98, 60);

        jLabelReservationBookCodeSample.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelReservationBookCodeSample.setText("<html><p align=\"center\">Code</p>Examplaire:</html>");
        jPanelReservations.add(jLabelReservationBookCodeSample);
        jLabelReservationBookCodeSample.setBounds(620, 10, 90, 40);
        jPanelReservations.add(jTextFieldReservationBookCodeSample);
        jTextFieldReservationBookCodeSample.setBounds(700, 10, 210, 38);

        jTabbedPane.addTab("Réservations", jPanelReservations);

        jPanelReservation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nouvelle Réservation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanelReservationLayout = new javax.swing.GroupLayout(jPanelReservation);
        jPanelReservation.setLayout(jPanelReservationLayout);
        jPanelReservationLayout.setHorizontalGroup(
            jPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelReservationLayout.setVerticalGroup(
            jPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
                    .addComponent(jPanelReservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookClear;
    private javax.swing.JButton jButtonBookDelete;
    private javax.swing.JButton jButtonBookDetails;
    private javax.swing.JButton jButtonBookReserve;
    private javax.swing.JButton jButtonBookSave;
    private javax.swing.JButton jButtonClientClear;
    private javax.swing.JButton jButtonClientDelete;
    private javax.swing.JButton jButtonClientDetails;
    private javax.swing.JButton jButtonClientReserve;
    private javax.swing.JButton jButtonClientSave;
    private javax.swing.JButton jButtonReservationCancel;
    private javax.swing.JButton jButtonReservationClear;
    private javax.swing.JButton jButtonReservationFinish;
    private javax.swing.JButton jButtonReservationRenew;
    private javax.swing.JCheckBox jCheckBoxBookRare;
    private javax.swing.JCheckBox jCheckBoxClientValid;
    private javax.swing.JCheckBox jCheckBoxReservationRare;
    private javax.swing.JLabel jLabelBookAuthors;
    private javax.swing.JLabel jLabelBookEdition;
    private javax.swing.JLabel jLabelBookEditor;
    private javax.swing.JLabel jLabelBookFormat;
    private javax.swing.JLabel jLabelBookISBN;
    private javax.swing.JLabel jLabelBookPrice;
    private javax.swing.JLabel jLabelBookTitle;
    private javax.swing.JLabel jLabelBookYear;
    private javax.swing.JLabel jLabelClientAddress;
    private javax.swing.JLabel jLabelClientCity;
    private javax.swing.JLabel jLabelClientCode;
    private javax.swing.JLabel jLabelClientDocConfirmation;
    private javax.swing.JLabel jLabelClientEmail;
    private javax.swing.JLabel jLabelClientId;
    private javax.swing.JLabel jLabelClientLastName;
    private javax.swing.JLabel jLabelClientName;
    private javax.swing.JLabel jLabelClientPhone;
    private javax.swing.JLabel jLabelClientState;
    private javax.swing.JLabel jLabelClientZIPCode;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelEditionLanguage;
    private javax.swing.JLabel jLabelEditionYear;
    private javax.swing.JLabel jLabelNumberPages;
    private javax.swing.JLabel jLabelOriginalLanguage;
    private javax.swing.JLabel jLabelPenalityPrice;
    private javax.swing.JLabel jLabelReservationBookCodeSample;
    private javax.swing.JLabel jLabelReservationBookISBN;
    private javax.swing.JLabel jLabelReservationBookName;
    private javax.swing.JLabel jLabelReservationClientCode;
    private javax.swing.JLabel jLabelReservationClientName;
    private javax.swing.JLabel jLabelReservationDate;
    private javax.swing.JLabel jLabelReservationReturnDate;
    private javax.swing.JLabel jLabelReservationStatus;
    private javax.swing.JLabel jLabelSampleCode;
    private javax.swing.JLabel jLabelTotalSamples;
    private javax.swing.JPanel jPanelBooks;
    private javax.swing.JPanel jPanelClients;
    private javax.swing.JPanel jPanelReservation;
    private javax.swing.JPanel jPanelReservations;
    private javax.swing.JScrollPane jScrollPaneBook;
    private javax.swing.JScrollPane jScrollPaneClient;
    private javax.swing.JScrollPane jScrollPaneReservations;
    private javax.swing.JSeparator jSeparatorClientAddress;
    private javax.swing.JSeparator jSeparatorClientInfo;
    private javax.swing.JSeparator jSeparatorReservationBook;
    private javax.swing.JSeparator jSeparatorReservationClient;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableBooks;
    private javax.swing.JTable jTableClients;
    private javax.swing.JTable jTableReservations;
    private javax.swing.JTextField jTextFieldBookAuthors;
    private javax.swing.JTextField jTextFieldBookEdition;
    private javax.swing.JTextField jTextFieldBookFormat;
    private javax.swing.JTextField jTextFieldBookISBN;
    private javax.swing.JTextField jTextFieldBookPrice;
    private javax.swing.JTextField jTextFieldBookSearch;
    private javax.swing.JTextField jTextFieldBookTitle;
    private javax.swing.JTextField jTextFieldBookYear;
    private javax.swing.JTextField jTextFieldClientAddress;
    private javax.swing.JTextField jTextFieldClientCity;
    private javax.swing.JTextField jTextFieldClientCode;
    private javax.swing.JTextField jTextFieldClientEmail;
    private javax.swing.JTextField jTextFieldClientId;
    private javax.swing.JTextField jTextFieldClientLastName;
    private javax.swing.JTextField jTextFieldClientName;
    private javax.swing.JTextField jTextFieldClientPhone;
    private javax.swing.JTextField jTextFieldClientSearch;
    private javax.swing.JTextField jTextFieldClientState;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldDocVerification;
    private javax.swing.JTextField jTextFieldEditionLanguage;
    private javax.swing.JTextField jTextFieldEditionYear;
    private javax.swing.JTextField jTextFieldEditor;
    private javax.swing.JTextField jTextFieldNumberPages;
    private javax.swing.JTextField jTextFieldOriginalLanguage;
    private javax.swing.JTextField jTextFieldPenalityPrice;
    private javax.swing.JTextField jTextFieldReservationBookCodeSample;
    private javax.swing.JTextField jTextFieldReservationBookISBN;
    private javax.swing.JTextField jTextFieldReservationBookName;
    private javax.swing.JTextField jTextFieldReservationClientCode;
    private javax.swing.JTextField jTextFieldReservationClientName;
    private javax.swing.JTextField jTextFieldReservationDate;
    private javax.swing.JTextField jTextFieldReservationReturnDate;
    private javax.swing.JTextField jTextFieldReservationSearch;
    private javax.swing.JTextField jTextFieldReservationStatus;
    private javax.swing.JTextField jTextFieldSampleCode;
    private javax.swing.JTextField jTextFieldTotalSamples;
    private javax.swing.JTextField jTextFieldZIPCode;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonBookClear() {
        return jButtonBookClear;
    }

    public JButton getjButtonBookDelete() {
        return jButtonBookDelete;
    }

    public JButton getjButtonBookDetails() {
        return jButtonBookDetails;
    }

    public JButton getjButtonBookReserve() {
        return jButtonBookReserve;
    }

    public JButton getjButtonBookSave() {
        return jButtonBookSave;
    }

    public JButton getjButtonClientClear() {
        return jButtonClientClear;
    }

    public JButton getjButtonClientDelete() {
        return jButtonClientDelete;
    }

    public JButton getjButtonClientDetails() {
        return jButtonClientDetails;
    }

    public JButton getjButtonClientReserve() {
        return jButtonClientReserve;
    }

    public JButton getjButtonClientSave() {
        return jButtonClientSave;
    }

    public JButton getjButtonReservationCancel() {
        return jButtonReservationCancel;
    }

    public JButton getjButtonReservationClear() {
        return jButtonReservationClear;
    }

    public JButton getjButtonReservationFinish() {
        return jButtonReservationFinish;
    }

    public JButton getjButtonReservationRenew() {
        return jButtonReservationRenew;
    }

    public JCheckBox getjCheckBoxBookRare() {
        return jCheckBoxBookRare;
    }

    public JCheckBox getjCheckBoxClientValid() {
        return jCheckBoxClientValid;
    }

    public JCheckBox getjCheckBoxReservationRare() {
        return jCheckBoxReservationRare;
    }

    public JTabbedPane getjTabbedPane() {
        return jTabbedPane;
    }

    public JTable getjTableBooks() {
        return jTableBooks;
    }

    public JTable getjTableClients() {
        return jTableClients;
    }

    public JTable getjTableReservations() {
        return jTableReservations;
    }

    public JTextField getjTextFieldBookAuthors() {
        return jTextFieldBookAuthors;
    }

    public JTextField getjTextFieldBookEdition() {
        return jTextFieldBookEdition;
    }

    public JTextField getjTextFieldBookFormat() {
        return jTextFieldBookFormat;
    }

    public JTextField getjTextFieldBookISBN() {
        return jTextFieldBookISBN;
    }

    public JTextField getjTextFieldBookPrice() {
        return jTextFieldBookPrice;
    }

    public JTextField getjTextFieldBookSearch() {
        return jTextFieldBookSearch;
    }

    public JTextField getjTextFieldBookTitle() {
        return jTextFieldBookTitle;
    }

    public JTextField getjTextFieldBookYear() {
        return jTextFieldBookYear;
    }

    public JTextField getjTextFieldClientAddress() {
        return jTextFieldClientAddress;
    }

    public JTextField getjTextFieldClientCity() {
        return jTextFieldClientCity;
    }

    public JTextField getjTextFieldClientCode() {
        return jTextFieldClientCode;
    }

    public JTextField getjTextFieldClientEmail() {
        return jTextFieldClientEmail;
    }

    public JTextField getjTextFieldClientId() {
        return jTextFieldClientId;
    }

    public JTextField getjTextFieldClientLastName() {
        return jTextFieldClientLastName;
    }

    public JTextField getjTextFieldClientName() {
        return jTextFieldClientName;
    }

    public JTextField getjTextFieldClientPhone() {
        return jTextFieldClientPhone;
    }

    public JTextField getjTextFieldClientSearch() {
        return jTextFieldClientSearch;
    }

    public JTextField getjTextFieldClientState() {
        return jTextFieldClientState;
    }

    public JTextField getjTextFieldCountry() {
        return jTextFieldCountry;
    }

    public JTextField getjTextFieldDocVerification() {
        return jTextFieldDocVerification;
    }

    public JTextField getjTextFieldEditionLanguage() {
        return jTextFieldEditionLanguage;
    }

    public JTextField getjTextFieldEditionYear() {
        return jTextFieldEditionYear;
    }

    public JTextField getjTextFieldEditor() {
        return jTextFieldEditor;
    }

    public JTextField getjTextFieldNumberPages() {
        return jTextFieldNumberPages;
    }

    public JTextField getjTextFieldOriginalLanguage() {
        return jTextFieldOriginalLanguage;
    }

    public JTextField getjTextFieldPenalityPrice() {
        return jTextFieldPenalityPrice;
    }

    public JTextField getjTextFieldReservationBookCodeSample() {
        return jTextFieldReservationBookCodeSample;
    }

    public JTextField getjTextFieldReservationBookISBN() {
        return jTextFieldReservationBookISBN;
    }

    public JTextField getjTextFieldReservationBookName() {
        return jTextFieldReservationBookName;
    }

    public JTextField getjTextFieldReservationClientCode() {
        return jTextFieldReservationClientCode;
    }

    public JTextField getjTextFieldReservationClientName() {
        return jTextFieldReservationClientName;
    }

    public JTextField getjTextFieldReservationDate() {
        return jTextFieldReservationDate;
    }

    public JTextField getjTextFieldReservationReturnDate() {
        return jTextFieldReservationReturnDate;
    }

    public JTextField getjTextFieldReservationSearch() {
        return jTextFieldReservationSearch;
    }

    public JTextField getjTextFieldReservationStatus() {
        return jTextFieldReservationStatus;
    }

    public JTextField getjTextFieldSampleCode() {
        return jTextFieldSampleCode;
    }

    public JTextField getjTextFieldTotalSamples() {
        return jTextFieldTotalSamples;
    }

    public JTextField getjTextFieldZIPCode() {
        return jTextFieldZIPCode;
    }

}
