-- MySQL Workbench Synchronization
-- Generated: 2018-07-15 21:09
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Henrique Nascimento

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `library-db`.`SYSTEM_USER` (
  `ID_SYSTEM_USER` INT(11) NOT NULL AUTO_INCREMENT,
  `CD_USER` VARCHAR(7) NOT NULL,
  `DS_PASSWORD` VARCHAR(45) NOT NULL,
  `ID_SYSTEM_USER_TYPE` INT(11) NOT NULL,
  `FL_ACTIVE` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_SYSTEM_USER`),
  INDEX `IDX_SYSTEM_USER_TYPE` (`ID_SYSTEM_USER_TYPE` ASC),
  UNIQUE INDEX `UQ_CODE_USER` (`CD_USER` ASC),
  CONSTRAINT `FK_SYSTEM_USER_TYPE`
    FOREIGN KEY (`ID_SYSTEM_USER_TYPE`)
    REFERENCES `library-db`.`SYSTEM_USER_TYPE` (`ID_SYSTEM_USER_TYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`SYSTEM_USER_TYPE` (
  `ID_SYSTEM_USER_TYPE` INT(11) NOT NULL AUTO_INCREMENT,
  `DS_TYPE` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`ID_SYSTEM_USER_TYPE`),
  UNIQUE INDEX `UQ_SYSTEM_USER_TYPE` (`DS_TYPE` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`CLIENT` (
  `ID_CLIENT` INT(11) NOT NULL AUTO_INCREMENT,
  `NM_NAME` VARCHAR(20) NOT NULL,
  `NM_LAST_NAME` VARCHAR(20) NOT NULL,
  `DS_ID` VARCHAR(15) NOT NULL COMMENT 'Any official document emitted by the government.',
  `DS_PHONE_NUMBER` VARCHAR(20) NOT NULL,
  `DS_EMAIL` VARCHAR(50) NULL DEFAULT NULL,
  `ID_ADDRESS` INT(11) NOT NULL,
  `ID_SYSTEM_USER` INT(11) NOT NULL,
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENT`),
  INDEX `IDX_CLIENT_SYSTEM_USER` (`ID_SYSTEM_USER` ASC),
  INDEX `IDX_CLIENT_ADDRESS` (`ID_ADDRESS` ASC),
  UNIQUE INDEX `UQ_CLIENT_SYSTEM_USER` (`ID_SYSTEM_USER` ASC),
  UNIQUE INDEX `UQ_CLIENT_ID` (`DS_ID` ASC),
  CONSTRAINT `FK_CLIENT_SYSTEM_USER`
    FOREIGN KEY (`ID_SYSTEM_USER`)
    REFERENCES `library-db`.`SYSTEM_USER` (`ID_SYSTEM_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CLIENT_ADDRESS`
    FOREIGN KEY (`ID_ADDRESS`)
    REFERENCES `library-db`.`ADDRESS` (`ID_ADDRESS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`ADDRESS` (
  `ID_ADDRESS` INT(11) NOT NULL AUTO_INCREMENT,
  `DS_ADDRESS` VARCHAR(70) NOT NULL,
  `NM_CITY` VARCHAR(25) NULL DEFAULT NULL,
  `NM_STATE` VARCHAR(25) NULL DEFAULT NULL,
  `NM_COUNTRY` VARCHAR(25) NULL DEFAULT NULL,
  `DS_ZIP_CODE` VARCHAR(8) NULL DEFAULT NULL,
  `DS_ADDRESS_PROOF` VARCHAR(20) NULL DEFAULT NULL,
  `FL_VALID` CHAR NOT NULL DEFAULT 'N',
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ADDRESS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`MANAGER_USER` (
  `ID_MANAGER_USER` INT(11) NOT NULL AUTO_INCREMENT,
  `NM_NAME` VARCHAR(20) NOT NULL,
  `NM_LAST_NAME` VARCHAR(20) NOT NULL,
  `ID_SYSTEM_USER` INT(11) NOT NULL,
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_MANAGER_USER`),
  INDEX `IDX_MANAGER_SYSTEM_USER` (`ID_SYSTEM_USER` ASC),
  UNIQUE INDEX `UQ_MANAGER_SYSTEM_USER` (`ID_SYSTEM_USER` ASC),
  CONSTRAINT `FK_MANAGER_SYSTEM_USER`
    FOREIGN KEY (`ID_SYSTEM_USER`)
    REFERENCES `library-db`.`SYSTEM_USER` (`ID_SYSTEM_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`BOOK` (
  `ID_BOOK` INT(11) NOT NULL AUTO_INCREMENT,
  `NM_TITLE` VARCHAR(150) NOT NULL,
  `NR_YEAR` INT(4) NOT NULL,
  `DS_LANGUAGE` VARCHAR(25) NOT NULL,
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_BOOK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`BOOK_EDITION` (
  `ID_BOOK_EDITION` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_BOOK` INT(11) NOT NULL,
  `ID_PUBLISHER` INT(11) NOT NULL,
  `CD_ISBN` VARCHAR(15) NOT NULL,
  `DS_EDITION` VARCHAR(25) NOT NULL,
  `NM_YEAR` INT(4) NOT NULL,
  `DS_FORMAT` VARCHAR(25) NOT NULL,
  `NM_TOTAL_PAGES` INT(6) NOT NULL,
  `VL_PENALTY_PRICE` DECIMAL(7,2) NOT NULL,
  `VL_BOOK_PRICE` DECIMAL(7,2) NOT NULL,
  `DS_LANGUAGE` VARCHAR(25) NOT NULL,
  `FL_RARE` CHAR NOT NULL DEFAULT 'N',
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_BOOK_EDITION`),
  INDEX `IDX_EDITION_BOOK` (`ID_BOOK` ASC),
  INDEX `IDX_EDITION_PUBLISHER` (`ID_PUBLISHER` ASC),
  UNIQUE INDEX `UQ_EDITION_ISBN` (`CD_ISBN` ASC, `DS_EDITION` ASC),
  CONSTRAINT `FK_EDITION_BOOK`
    FOREIGN KEY (`ID_BOOK`)
    REFERENCES `library-db`.`BOOK` (`ID_BOOK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_EDITION_PUBLISHER`
    FOREIGN KEY (`ID_PUBLISHER`)
    REFERENCES `library-db`.`PUBLISHER` (`ID_PUBLISHER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`BOOK_SAMPLE` (
  `ID_BOOK_SAMPLE` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_BOOK_EDITION` INT(11) NOT NULL,
  `CD_CODE` VARCHAR(10) NOT NULL,
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_BOOK_SAMPLE`),
  INDEX `IDX_SAMPLE_EDITION` (`ID_BOOK_EDITION` ASC),
  UNIQUE INDEX `UQ_SAMPLE_CODE` (`CD_CODE` ASC),
  CONSTRAINT `FK_SAMPLE_EDITION`
    FOREIGN KEY (`ID_BOOK_EDITION`)
    REFERENCES `library-db`.`BOOK_EDITION` (`ID_BOOK_EDITION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`AUTHOR` (
  `ID_AUTHOR` INT(11) NOT NULL AUTO_INCREMENT,
  `NM_NAME` VARCHAR(45) NOT NULL,
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_AUTHOR`),
  UNIQUE INDEX `UQ_AUTHOR_NAME` (`NM_NAME` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`PUBLISHER` (
  `ID_PUBLISHER` INT(11) NOT NULL AUTO_INCREMENT,
  `NM_NAME` VARCHAR(45) NOT NULL,
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PUBLISHER`),
  UNIQUE INDEX `UQ_PUBLISHER_NAME` (`NM_NAME` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`BOOK_EDITION_AUTHOR` (
  `ID_BOOK_EDITION` INT(11) NOT NULL,
  `ID_AUTHOR` INT(11) NOT NULL,
  PRIMARY KEY (`ID_BOOK_EDITION`, `ID_AUTHOR`),
  INDEX `IDX_AUTHOR_EDITION` (`ID_AUTHOR` ASC),
  UNIQUE INDEX `UQ_BOOK_EDITION_AUTHOR` (`ID_BOOK_EDITION` ASC, `ID_AUTHOR` ASC),
  CONSTRAINT `FK_EDITION_AUTHOR`
    FOREIGN KEY (`ID_BOOK_EDITION`)
    REFERENCES `library-db`.`BOOK_EDITION` (`ID_BOOK_EDITION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AUTHOR_EDITION`
    FOREIGN KEY (`ID_AUTHOR`)
    REFERENCES `library-db`.`AUTHOR` (`ID_AUTHOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`BOOK_WAITING_LIST` (
  `ID_BOOK_WAITING_LIST` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_BOOK_EDITION` INT(11) NOT NULL,
  `ID_CLIENT` INT(11) NOT NULL,
  `ID_BOOK_WAITING_LIST_STATUS` INT(11) NOT NULL,
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_BOOK_WAITING_LIST`),
  INDEX `IDX_BOOK_WAITING_STATUS` (`ID_BOOK_WAITING_LIST_STATUS` ASC),
  INDEX `IDX_BOOK_WAITING_CLIENT` (`ID_CLIENT` ASC),
  INDEX `IDX_BOOK_WAITING_BOOK` (`ID_BOOK_EDITION` ASC),
  CONSTRAINT `FK_BOOK_WAITING_STATUS`
    FOREIGN KEY (`ID_BOOK_WAITING_LIST_STATUS`)
    REFERENCES `library-db`.`BOOK_WAITING_LIST_STATUS` (`ID_BOOK_WAITING_LIST_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BOOK_WAITING_CLIENT`
    FOREIGN KEY (`ID_CLIENT`)
    REFERENCES `library-db`.`CLIENT` (`ID_CLIENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BOOK_WAITING_BOOK`
    FOREIGN KEY (`ID_BOOK_EDITION`)
    REFERENCES `library-db`.`BOOK_EDITION` (`ID_BOOK_EDITION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`BOOK_WAITING_LIST_STATUS` (
  `ID_BOOK_WAITING_LIST_STATUS` INT(11) NOT NULL AUTO_INCREMENT,
  `DS_STATUS` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_BOOK_WAITING_LIST_STATUS`),
  UNIQUE INDEX `UQ_BOOK_WAITING_LIST_STATUS` (`DS_STATUS` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`BOOK_RESERVATION` (
  `ID_BOOK_RESERVATION` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_BOOK_SAMPLE` INT(11) NOT NULL,
  `ID_CLIENT` INT(11) NOT NULL,
  `ID_BOOK_RESERVATION_STATUS` INT(11) NOT NULL,
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_BOOK_RESERVATION`),
  INDEX `IDX_BOOK_RESERVATION_SAMPLE` (`ID_BOOK_SAMPLE` ASC),
  INDEX `IDX_BOOK_RESERVATION_CLIENT` (`ID_CLIENT` ASC),
  INDEX `IDX_BOOK_RESERVATION_STATUS` (`ID_BOOK_RESERVATION_STATUS` ASC),
  CONSTRAINT `FK_BOOK_RESERVATION_SAMPLE`
    FOREIGN KEY (`ID_BOOK_SAMPLE`)
    REFERENCES `library-db`.`BOOK_SAMPLE` (`ID_BOOK_SAMPLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BOOK_RESERVATION_CLIENT`
    FOREIGN KEY (`ID_CLIENT`)
    REFERENCES `library-db`.`CLIENT` (`ID_CLIENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BOOK_RESERVATION_STATUS`
    FOREIGN KEY (`ID_BOOK_RESERVATION_STATUS`)
    REFERENCES `library-db`.`BOOK_RESERVATION_STATUS` (`ID_BOOK_RESERVATION_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`BOOK_RESERVATION_STATUS` (
  `ID_BOOK_RESERVATION_STATUS` INT(11) NOT NULL AUTO_INCREMENT,
  `DS_STATUS` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID_BOOK_RESERVATION_STATUS`),
  UNIQUE INDEX `UQ_BOOK_RESERVATION_STATUS` (`DS_STATUS` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`ROOM_RESERVATION` (
  `ID_ROOM_RESERVATION` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_ROOM` INT(11) NOT NULL,
  `ID_CLIENT` INT(11) NOT NULL,
  `ID_BOOK_EDITION` INT(11) NOT NULL,
  `DT_RESERVATION` DATE NOT NULL,
  `ID_ROOM_PERIOD` INT(11) NOT NULL,
  `ID_ROOM_RESERVATION_STATUS` INT(11) NOT NULL,
  `DT_CREATION` DATETIME NOT NULL DEFAULT NOW(),
  `DT_MODIFICATION` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ROOM_RESERVATION`),
  INDEX `IDX_ROOM_RESERVATION_ROOM` (`ID_ROOM` ASC),
  INDEX `IDX_ROOM_RESERVATION_CLIENT` (`ID_CLIENT` ASC),
  INDEX `IDX_ROOM_RESERVATION_BOOK` (`ID_BOOK_EDITION` ASC),
  INDEX `IDX_ROOM_RESERVATION_PERIOD` (`ID_ROOM_PERIOD` ASC),
  INDEX `IDX_ROOM_RESERVATION_STATUS` (`ID_ROOM_RESERVATION_STATUS` ASC),
  UNIQUE INDEX `UQ_ROOM_RESERVATION` (`ID_CLIENT` ASC, `DT_RESERVATION` ASC, `ID_ROOM_PERIOD` ASC),
  CONSTRAINT `FK_ROOM_RESERVATION_ROOM`
    FOREIGN KEY (`ID_ROOM`)
    REFERENCES `library-db`.`ROOM` (`ID_ROOM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ROOM_RESERVATION_CLIENT`
    FOREIGN KEY (`ID_CLIENT`)
    REFERENCES `library-db`.`CLIENT` (`ID_CLIENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ROOM_RESERVATION_BOOK`
    FOREIGN KEY (`ID_BOOK_EDITION`)
    REFERENCES `library-db`.`BOOK_EDITION` (`ID_BOOK_EDITION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ROOM_RESERVATION_PERIOD`
    FOREIGN KEY (`ID_ROOM_PERIOD`)
    REFERENCES `library-db`.`ROOM_PERIOD` (`ID_ROOM_PERIOD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ROOM_RESERVATION_STATUS`
    FOREIGN KEY (`ID_ROOM_RESERVATION_STATUS`)
    REFERENCES `library-db`.`ROOM_RESERVATION_STATUS` (`ID_ROOM_RESERVATION_STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`ROOM` (
  `ID_ROOM` INT(11) NOT NULL AUTO_INCREMENT,
  `CD_ROOM` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_ROOM`),
  UNIQUE INDEX `UQ_ROOM` (`CD_ROOM` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`ROOM_PERIOD` (
  `ID_ROOM_PERIOD` INT(11) NOT NULL AUTO_INCREMENT,
  `DS_PERIOD` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_ROOM_PERIOD`),
  UNIQUE INDEX `UQ_ROOM_PERIOD` (`DS_PERIOD` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `library-db`.`ROOM_RESERVATION_STATUS` (
  `ID_ROOM_RESERVATION_STATUS` INT(11) NOT NULL AUTO_INCREMENT,
  `DS_STATUS` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID_ROOM_RESERVATION_STATUS`),
  UNIQUE INDEX `UQ_ROOM_RESERVATION_STATUS` (`DS_STATUS` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
