INSERT INTO `library-db`.SYSTEM_USER_TYPE(ID_SYSTEM_USER_TYPE, DS_TYPE)
VALUES (1,'CLIENT');

INSERT INTO `library-db`.SYSTEM_USER(ID_SYSTEM_USER, CD_USER, DS_PASSWORD, ID_SYSTEM_USER_TYPE)
VALUES (1,'teste','e10adc3949ba59abbe56e057f20f883e', 1);

INSERT INTO `library-db`.AUTHOR(NM_NAME) VALUES('Martin,George R. R.');

INSERT INTO `library-db`.BOOK(NM_TITLE, NR_YEAR, DS_LANGUAGE) VALUES('A Tormenta de Espadas - As Crônicas de Gelo e Fogo', 2015, 'PORTUGAIS');

INSERT INTO `library-db`.PUBLISHER(NM_NAME) VALUES('Casa Da Palavra');

INSERT INTO `library-db`.BOOK_EDITION(ID_BOOK, ID_PUBLISHER, CD_ISBN, DS_EDITION, NM_YEAR, DS_FORMAT, NM_TOTAL_PAGES, VL_PENALTY_PRICE, VL_BOOK_PRICE, DS_LANGUAGE) 
VALUES(1, 1, '9788544102947', 'Edição comemorativa', 2015, 'PAPEL', 848, 2.0, 25.5, 'PORTUGAIS');

INSERT INTO `library-db`.BOOK_EDITION_AUTHOR VALUES(1,1);

INSERT INTO `library-db`.BOOK_SAMPLE(ID_BOOK_EDITION, CD_CODE) VALUES(1,'1'); /*Como é gerado o CD_CODE?*/

INSERT INTO `library-db`.BOOK_RESERVATION_STATUS(DS_STATUS) 
VALUES ('Pending'),('In Progress'),('Completed'),('Canceled'),('Deferred'),('Completed with Penalty');

INSERT INTO `library-db`.ROOM_PERIOD (CD_ROOM)
VALUES ('1')

INSERT INTO `library-db`.ROOM_RESERVATION_STATUS (DS_STATUS) 
VALUES ('Pending'),('In Progress'),('Completed'),('Canceled')

INSERT INTO `library-db`.ROOM_PERIOD (DS_PERIOD) VALUES ('MATIN'),('APRESMIDI')

