INSERT INTO AUTHOR(NM_NAME) VALUES('Martin,George R. R.');

INSERT INTO BOOK(NM_TITLE, NR_YEAR, DS_LANGUAGE) VALUES('A Tormenta de Espadas - As Crônicas de Gelo e Fogo', 2015, 'PORTUGAIS');

INSERT INTO PUBLISHER(NM_NAME) VALUES('Casa Da Palavra');

INSERT INTO BOOK_EDITION(ID_BOOK, ID_PUBLISHER, CD_ISBN, DS_EDITION, NM_YEAR, DS_FORMAT, NM_TOTAL_PAGES, VL_PENALTY_PRICE, VL_BOOK_PRICE, DS_LANGUAGE) 
VALUES(1, 1, '9788544102947', 'Edição comemorativa', 2015, 'PAPEL', 848, 2.0, 25.5, 'PORTUGAIS');

INSERT INTO BOOK_EDITION_AUTHOR VALUES(1,1);