-- USER
SELECT * FROM SYSTEM_USER;
SELECT * FROM MANAGER_USER;
SELECT * FROM CLIENT;

DELETE FROM SYSTEM_USER;
DELETE FROM MANAGER_USER;
-- USER

-- BOOK
SELECT * FROM BOOK;
SELECT * FROM BOOK_EDITION;
SELECT * FROM BOOK_SAMPLE;
-- BOOK


SELECT * FROM ADDRESS;


SELECT * FROM BOOK_RESERVATION_STATUS;
SELECT * FROM BOOK_RESERVATION;

SELECT * FROM BOOK_SAMPLE bs 
WHERE bs.ID_BOOK_SAMPLE NOT IN(SELECT ID_BOOK_SAMPLE FROM BOOK_RESERVATION 
								WHERE ID_BOOK_RESERVATION_STATUS IN(1, 2, 5)) 
                                AND bs.ID_BOOK_EDITION = 6 LIMIT 1;
                                

                                
                                
                                SELECT ID_BOOK_SAMPLE FROM BOOK_RESERVATION 
								WHERE ID_BOOK_RESERVATION_STATUS NOT IN(2, 5);







SELECT * FROM CLIENT c 
INNER JOIN SYSTEM_USER su ON(c.ID_SYSTEM_USER = su.ID_SYSTEM_USER)
INNER JOIN ADDRESS a ON(c.ID_ADDRESS = a.ID_ADDRESS);

-- DOMAIN
SELECT * FROM SYSTEM_USER_TYPE;
SELECT * FROM BOOK_WAITING_LIST_STATUS;
SELECT * FROM BOOK_RESERVATION_STATUS;
SELECT * FROM ROOM;
SELECT * FROM ROOM_PERIOD;
SELECT * FROM ROOM_RESERVATION_STATUS;

DELETE FROM SYSTEM_USER_TYPE;
DELETE FROM BOOK_WAITING_LIST_STATUS;
DELETE FROM BOOK_RESERVATION_STATUS;
DELETE FROM ROOM;
DELETE FROM ROOM_PERIOD;
DELETE FROM ROOM_RESERVATION_STATUS;
-- DOMAIN

